# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blue/c_projects/newblue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blue/c_projects/newblue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blue/c_projects/newblue/CMakeFiles /home/blue/c_projects/newblue//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blue/c_projects/newblue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blue

# Build rule for target.
blue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blue
.PHONY : blue

# fast build rule for target.
blue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/build
.PHONY : blue/fast

#=============================================================================
# Target rules for targets named blue_static

# Build rule for target.
blue_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blue_static
.PHONY : blue_static

# fast build rule for target.
blue_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/build
.PHONY : blue_static/fast

blue/log.o: blue/log.cpp.o
.PHONY : blue/log.o

# target to build an object file
blue/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue/log.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/blue/log.cpp.o
.PHONY : blue/log.cpp.o

blue/log.i: blue/log.cpp.i
.PHONY : blue/log.i

# target to preprocess a source file
blue/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue/log.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/blue/log.cpp.i
.PHONY : blue/log.cpp.i

blue/log.s: blue/log.cpp.s
.PHONY : blue/log.s

# target to generate assembly for a file
blue/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue/log.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/blue/log.cpp.s
.PHONY : blue/log.cpp.s

blue/mthread.o: blue/mthread.cpp.o
.PHONY : blue/mthread.o

# target to build an object file
blue/mthread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue/mthread.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/blue/mthread.cpp.o
.PHONY : blue/mthread.cpp.o

blue/mthread.i: blue/mthread.cpp.i
.PHONY : blue/mthread.i

# target to preprocess a source file
blue/mthread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue/mthread.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/blue/mthread.cpp.i
.PHONY : blue/mthread.cpp.i

blue/mthread.s: blue/mthread.cpp.s
.PHONY : blue/mthread.s

# target to generate assembly for a file
blue/mthread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue/mthread.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/blue/mthread.cpp.s
.PHONY : blue/mthread.cpp.s

newblue/schedular.o: newblue/schedular.cpp.o
.PHONY : newblue/schedular.o

# target to build an object file
newblue/schedular.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/newblue/schedular.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/newblue/schedular.cpp.o
.PHONY : newblue/schedular.cpp.o

newblue/schedular.i: newblue/schedular.cpp.i
.PHONY : newblue/schedular.i

# target to preprocess a source file
newblue/schedular.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/newblue/schedular.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/newblue/schedular.cpp.i
.PHONY : newblue/schedular.cpp.i

newblue/schedular.s: newblue/schedular.cpp.s
.PHONY : newblue/schedular.s

# target to generate assembly for a file
newblue/schedular.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/newblue/schedular.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/newblue/schedular.cpp.s
.PHONY : newblue/schedular.cpp.s

thirdparty/llhttp-release-v9.2.0/src/api.o: thirdparty/llhttp-release-v9.2.0/src/api.c.o
.PHONY : thirdparty/llhttp-release-v9.2.0/src/api.o

# target to build an object file
thirdparty/llhttp-release-v9.2.0/src/api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/api.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/api.c.o
.PHONY : thirdparty/llhttp-release-v9.2.0/src/api.c.o

thirdparty/llhttp-release-v9.2.0/src/api.i: thirdparty/llhttp-release-v9.2.0/src/api.c.i
.PHONY : thirdparty/llhttp-release-v9.2.0/src/api.i

# target to preprocess a source file
thirdparty/llhttp-release-v9.2.0/src/api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/api.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/api.c.i
.PHONY : thirdparty/llhttp-release-v9.2.0/src/api.c.i

thirdparty/llhttp-release-v9.2.0/src/api.s: thirdparty/llhttp-release-v9.2.0/src/api.c.s
.PHONY : thirdparty/llhttp-release-v9.2.0/src/api.s

# target to generate assembly for a file
thirdparty/llhttp-release-v9.2.0/src/api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/api.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/api.c.s
.PHONY : thirdparty/llhttp-release-v9.2.0/src/api.c.s

thirdparty/llhttp-release-v9.2.0/src/http.o: thirdparty/llhttp-release-v9.2.0/src/http.c.o
.PHONY : thirdparty/llhttp-release-v9.2.0/src/http.o

# target to build an object file
thirdparty/llhttp-release-v9.2.0/src/http.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/http.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/http.c.o
.PHONY : thirdparty/llhttp-release-v9.2.0/src/http.c.o

thirdparty/llhttp-release-v9.2.0/src/http.i: thirdparty/llhttp-release-v9.2.0/src/http.c.i
.PHONY : thirdparty/llhttp-release-v9.2.0/src/http.i

# target to preprocess a source file
thirdparty/llhttp-release-v9.2.0/src/http.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/http.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/http.c.i
.PHONY : thirdparty/llhttp-release-v9.2.0/src/http.c.i

thirdparty/llhttp-release-v9.2.0/src/http.s: thirdparty/llhttp-release-v9.2.0/src/http.c.s
.PHONY : thirdparty/llhttp-release-v9.2.0/src/http.s

# target to generate assembly for a file
thirdparty/llhttp-release-v9.2.0/src/http.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/http.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/http.c.s
.PHONY : thirdparty/llhttp-release-v9.2.0/src/http.c.s

thirdparty/llhttp-release-v9.2.0/src/llhttp.o: thirdparty/llhttp-release-v9.2.0/src/llhttp.c.o
.PHONY : thirdparty/llhttp-release-v9.2.0/src/llhttp.o

# target to build an object file
thirdparty/llhttp-release-v9.2.0/src/llhttp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/llhttp.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/llhttp.c.o
.PHONY : thirdparty/llhttp-release-v9.2.0/src/llhttp.c.o

thirdparty/llhttp-release-v9.2.0/src/llhttp.i: thirdparty/llhttp-release-v9.2.0/src/llhttp.c.i
.PHONY : thirdparty/llhttp-release-v9.2.0/src/llhttp.i

# target to preprocess a source file
thirdparty/llhttp-release-v9.2.0/src/llhttp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/llhttp.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/llhttp.c.i
.PHONY : thirdparty/llhttp-release-v9.2.0/src/llhttp.c.i

thirdparty/llhttp-release-v9.2.0/src/llhttp.s: thirdparty/llhttp-release-v9.2.0/src/llhttp.c.s
.PHONY : thirdparty/llhttp-release-v9.2.0/src/llhttp.s

# target to generate assembly for a file
thirdparty/llhttp-release-v9.2.0/src/llhttp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/thirdparty/llhttp-release-v9.2.0/src/llhttp.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blue_static.dir/build.make CMakeFiles/blue_static.dir/thirdparty/llhttp-release-v9.2.0/src/llhttp.c.s
.PHONY : thirdparty/llhttp-release-v9.2.0/src/llhttp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... blue"
	@echo "... blue_static"
	@echo "... blue/log.o"
	@echo "... blue/log.i"
	@echo "... blue/log.s"
	@echo "... blue/mthread.o"
	@echo "... blue/mthread.i"
	@echo "... blue/mthread.s"
	@echo "... newblue/schedular.o"
	@echo "... newblue/schedular.i"
	@echo "... newblue/schedular.s"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/api.o"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/api.i"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/api.s"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/http.o"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/http.i"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/http.s"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/llhttp.o"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/llhttp.i"
	@echo "... thirdparty/llhttp-release-v9.2.0/src/llhttp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

